# 1. Konfigurasi Server
backend:
  name: github
  repo: Narimarishi/benak-insan-web
  branch: main

# 2. Pengaturan Media & Gambar
media_folder: "static/gambar" # Tempat CMS menyimpan gambar yang di-upload klien
public_folder: "/gambar" # URL yang dicetak CMS ke dalam artikel

# 3. Merancang Formulir Input (Koleksi Artikel)
collections:
  - name: "artikel"
    label: "Artikel & Materi"
    folder: "content/posts"
    # --- BARIS SAKTI UNTUK MEMBACA FOLDER (PAGE BUNDLES) ---
    path: "{{slug}}/index" 
    # --------------------------------------------------------
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul Materi", name: "title", widget: "string"}
      - {label: "Tanggal Terbit", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "categories", widget: "list", required: false}
      - {label: "Tag (Kata Kunci)", name: "tags", widget: "list", required: false}
      - {label: "Gambar Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Isi Teks Artikel", name: "body", widget: "markdown"}